name: whisper_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.3.9


assets:
  - assets/
  - assets/images/**


flutter:
  uses-material-design: true

