import 'package:whisper_box/template.dart';
import 'package:whisper_box/user.dart';

final templates = [
  Template(
      label: '오늘의 TMI',
      contents: '오늘의 TMI를 작성해보세요.\nex) 오늘 보도블럭을 핥았는데 달더라구요. '),
  Template(
      label: '요즘 관심사',
      contents: '관심사에 대해 이야기해봐요.\nex) 요즘 아침마다 독기있게 러닝을 하고 있어요.'),
  Template(
      label: '오늘 일정',
      contents: '오늘 일정에 대해 이야기해보세요\nex) 아…오늘 사이드 플젝 끝낼 수 있을까요?ㅠ 망해따…'),
  Template(
      label: '이상형', contents: '이상형에 대해 이야기해봐요.\nex) 저는 INFP만 수집하는 취향이에요. '),
];

final anonymous = ['익명의 오리너구리', '익명의 물풍선', '익명의 물고기'];
final List<User> users = [
  User(nickname: 'Wade', name: '김현기'),
  User(nickname: 'Yeony', name: '남도연'),
  User(nickname: 'Gigi', name: '박지원'),
  User(nickname: 'Murphy', name: '유정민'),
  User(nickname: 'Finn', name: '정종문'),
  User(nickname: 'OneThing', name: '천은송'),
  User(nickname: 'Junia', name: '최예은'),
  User(nickname: 'Jacob', name: '김경주'),
  User(nickname: 'Luke', name: '문승찬'),
  User(nickname: 'Pray', name: '양동균'),
  User(nickname: 'iL', name: '여성일'),
  User(nickname: 'Paran', name: '연선애'),
  User(nickname: 'Bota', name: '윤보라'),
  User(nickname: 'Daisy', name: null),
  User(nickname: 'JIN', name: '강진'),
  User(nickname: 'Noah', name: '김선환'),
  User(nickname: 'Brandnew', name: '박신규'),
  User(nickname: 'Demian', name: '유경모'),
  User(nickname: 'Mingky', name: '윤민경'),
  User(nickname: 'Hidy', name: '이윤서'),
  User(nickname: 'Cherry', name: '임서연'),
  User(nickname: 'Isla', name: '길연진'),
  User(nickname: 'Weaver', name: '김미나'),
  User(nickname: 'Paidion', name: '김준구'),
  User(nickname: 'Joid', name: '나현흠'),
  User(nickname: 'Hari', name: '윤하정'),
  User(nickname: 'Monica', name: '이가원'),
  User(nickname: 'Minbol', name: '이보민'),
  User(nickname: 'Dora', name: null),
  User(nickname: 'Moo', name: '김무찬'),
  User(nickname: 'J', name: '김지혜'),
  User(nickname: 'Chloe', name: '박현지'),
  User(nickname: 'Kirby', name: '양서린'),
  User(nickname: 'Steve', name: '이은수'),
  User(nickname: 'Hama', name: '이주함'),
  User(nickname: 'Angie 🪽', name: '장수연'),
  User(nickname: 'Riel', name: '권윤진'),
  User(nickname: 'Miru', name: '김성현'),
  User(nickname: 'Mumin', name: '남기민'),
  User(nickname: 'Libby', name: '배연경'),
  User(nickname: 'Lucas', name: '유선종'),
  User(nickname: 'Bob', name: '임영택'),
  User(nickname: 'Elena', name: '김지윤'),
  User(nickname: 'Glowny', name: '박승은'),
  User(nickname: 'JudyJ', name: '이주현'),
  User(nickname: 'Woody', name: '이창건'),
  User(nickname: 'Dewy', name: '김도연'),
  User(nickname: 'Julianne', name: '이주은'),
  User(nickname: 'Rundo', name: '이헌도'),
  User(nickname: 'Howard', name: null),
  User(nickname: 'May', name: '김민정'),
  User(nickname: 'Echo', name: '신민규'),
  User(nickname: 'Ted', name: '한건희'),
  User(nickname: 'Bin', name: '황유빈'),
  User(nickname: 'Nyx', name: null),
  User(nickname: 'KON', name: null),
  User(nickname: 'Sandeul', name: '양희준'),
  User(nickname: 'Ian', name: '이승진'),
  User(nickname: 'Ivy', name: '이현주'),
  User(nickname: 'Herry', name: '정혜승'),
  User(nickname: 'Lemon', name: '정희균'),
  User(nickname: 'Loa', name: '최희진'),
  User(nickname: 'Isaac', name: null),
  User(nickname: 'Sera', name: '김이준'),
  User(nickname: 'ssol', name: '석민솔'),
  User(nickname: 'Jun', name: '임준혁'),
  User(nickname: 'Avery', name: null),
  User(nickname: 'ARI', name: '박민아'),
  User(nickname: 'Isa', name: '우정아'),
  User(nickname: 'Taki', name: '이준희'),
  User(nickname: 'Zani', name: '창희'),
  User(nickname: 'Jenna', name: null),
  User(nickname: 'Jiku', name: null),
  User(nickname: 'Pherd', name: '구태현'),
  User(nickname: 'Yan', name: '아우신얀'),
  User(nickname: 'Cheshire', name: '조계성'),
  User(nickname: 'Heggy', name: '조혁재'),
  User(nickname: 'Nike', name: '최승리'),
  User(nickname: 'Frank', name: null),
  User(nickname: 'Rohd', name: '길정수'),
  User(nickname: 'Lina', name: '김민경'),
  User(nickname: 'Rama', name: '문형근'),
  User(nickname: 'Yuha', name: '신유하'),
  User(nickname: 'Singsing', name: '이시은'),
  User(nickname: 'Erin', name: '차정인'),
  User(nickname: 'Judy', name: null),
  User(nickname: 'Viera', name: '김채원'),
  User(nickname: 'Min', name: '민채영'),
  User(nickname: 'HappyJay', name: '장성태'),
  User(nickname: 'gabi', name: '전유진'),
  User(nickname: 'Dean', name: '정송헌'),
  User(nickname: 'Zhen', name: '조민정'),
  User(nickname: 'Presence', name: '김규학'),
  User(nickname: 'Luka', name: '김무성'),
  User(nickname: 'Theo', name: '김성민'),
  User(nickname: 'Eddey', name: '김재윤'),
  User(nickname: 'Seo', name: null),
  User(nickname: 'Ken', name: '김현진'),
  User(nickname: 'RIA', name: '신유민'),
  User(nickname: 'Sana', name: '오수아'),
  User(nickname: 'Jam', name: '이자민'),
  User(nickname: 'Simi', name: '장수민'),
  User(nickname: 'Kwango', name: '허찬욱'),
  User(nickname: 'Kinder', name: '김민석'),
  User(nickname: 'Excellenty', name: '문아영'),
  User(nickname: 'Sally', name: '이수빈'),
  User(nickname: 'Jerry', name: '장준하'),
  User(nickname: 'Anne', name: '진아현'),
  User(nickname: 'Enoch', name: '한혜빈'),
  User(nickname: 'Leeo', name: null),
  User(nickname: 'Wish', name: '김소원'),
  User(nickname: 'Jenki', name: '김현진'),
  User(nickname: 'Gus', name: '윤창현'),
  User(nickname: 'Jomi', name: '이호정'),
  User(nickname: 'Evan', name: '정희경'),
  User(nickname: 'Martin', name: '채지한'),
  User(nickname: 'Sena', name: '황세연'),
  User(nickname: 'Romak', name: '김준호'),
  User(nickname: 'Jeje', name: '박정욱'),
  User(nickname: 'Yoshi', name: '엄태형'),
  User(nickname: 'Emma', name: '이혜빈'),
  User(nickname: 'Kaia', name: '전가혜'),
  User(nickname: 'Yoon', name: '최윤'),
  User(nickname: 'Alex', name: '최정환'),
  User(nickname: 'MK', name: null),
  User(nickname: 'Ethan', name: '김동희'),
  User(nickname: 'Fine', name: '김순주'),
  User(nickname: 'Nika', name: '박난'),
  User(nickname: 'Bear', name: '성은관'),
  User(nickname: 'Noter', name: '소연수'),
  User(nickname: 'Mini', name: '이민재'),
  User(nickname: 'Three', name: '이슬'),
  User(nickname: 'One', name: '김동민'),
  User(nickname: 'Hong', name: '김윤홍'),
  User(nickname: 'Velko', name: '김진혁'),
  User(nickname: 'Kadan', name: '조재훈'),
  User(nickname: 'Jooni', name: '조혜준'),
  User(nickname: 'Jina', name: '진서영'),
  User(nickname: 'Jung', name: '최정인'),
  User(nickname: 'Nathan', name: null),
  User(nickname: 'ⒼⓄ Go', name: '고재현'),
  User(nickname: 'Taeni', name: '김태인'),
  User(nickname: 'Ito', name: '문창재'),
  User(nickname: 'Air', name: '양시준'),
  User(nickname: 'Dodin', name: '오서진'),
  User(nickname: 'Hyun', name: '이서현'),
  User(nickname: 'Mosae', name: '조민수'),
  User(nickname: 'Gil', name: '길지훈'),
  User(nickname: 'Coulson', name: '김민웅'),
  User(nickname: 'Karyn', name: '김하경'),
  User(nickname: 'Eifer', name: '유승재'),
  User(nickname: 'Wendy', name: '윤예람'),
  User(nickname: 'Nell', name: null),
  User(nickname: 'Powel', name: null),
  User(nickname: 'Saya', name: null),
  User(nickname: 'Elian', name: '김성현'),
  User(nickname: 'Leo', name: '김준철'),
  User(nickname: 'Berry', name: '배현진'),
  User(nickname: 'Yuu', name: '조유진'),
  User(nickname: 'Sky', name: '최하늘'),
  User(nickname: 'Root', name: '맹지주'),
  User(nickname: 'Zigu', name: '신지현'),
  User(nickname: 'Jack', name: '오세광'),
  User(nickname: 'Nayl', name: '이소진'),
  User(nickname: 'Tether', name: '차봉준'),
  User(nickname: 'Sup', name: null),
  User(nickname: 'Lumi', name: '정영진'),
  User(nickname: 'Friday', name: '김여운'),
  User(nickname: 'Joy', name: '강기쁨'),
  User(nickname: 'Snow', name: '김지하'),
  User(nickname: 'Jaeryong 째룡', name: '신재룡'),
  User(nickname: 'Baba', name: '유진식'),
  User(nickname: 'Ella', name: '이은서'),
  User(nickname: 'WAY', name: '이태연'),
  User(nickname: 'Ell', name: '한주연'),
  User(nickname: 'Elphie', name: '황제하'),
  User(nickname: 'Kave', name: '황지민'),
  User(nickname: 'Wonjun', name: null),
  User(nickname: 'Henry', name: null),
  User(nickname: 'Green', name: '고승아'),
  User(nickname: 'Skyler', name: '김유림'),
  User(nickname: 'Cerin', name: '서세린'),
  User(nickname: 'Paduck', name: '서용원'),
  User(nickname: 'Mary', name: '임희서'),
  User(nickname: 'My', name: '정민지'),
  User(nickname: 'Gyeong', name: '조운경'),
  User(nickname: 'Soop', name: '한수빈'),
  User(nickname: 'Oliver', name: '홍석호'),
  User(nickname: 'Daniely (L)', name: null),
  User(nickname: 'JeOng', name: null),
  User(nickname: 'Leon', name: null),
  User(nickname: 'peppr', name: null),
];
